<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Genogram"
    nsURI="http://genogram" nsPrefix="Genogram">
  <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DateOfBirth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DateOfDeath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Genogram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasRelations" upperBound="-1"
        eType="#//FamilyRelation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasEntities" upperBound="-1"
        eType="#//Entity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Man" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Woman" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Marriage" eSuperTypes="#//FamilyRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Engagement" eSuperTypes="#//FamilyRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cohabitation" eSuperTypes="#//FamilyRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="FamilyRelation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Woman"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Man"/>
  </eClassifiers>
</ecore:EPackage>
